# Generated by Django 4.0.5 on 2022-06-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('reviews', '0002_remove_review_movie_remove_review_user_review_critic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.movie'),
        ),
    ]
